#pragma config(Motor,  port1,           righback,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftback,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LSright,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LSback,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           clawupdowm,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           clawopenclose, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

	/*Riley, your code isn't bad :)
			Positives:
				You know how to use if, else if, and else :)
				You remember to turn off the motors you use in the if and else if statements :)
				You know how to implement the joysticks and the buttons on the controller :)
			Places to Improve:
				The tabbing of code is critical in readability when writing in ROBOTC
				When you write an if statement, the else if, and else statements should be the same indent over
				White space is your friend :P Please hit enter after each "chunk" of code to aid readability
				Comments are really helpful :P
				Please call the motors by the name you give them instead of port1, port2, etc.
				Your code works, but it would be easier to read if you made helper functions
					For example:
							void driveForward() {
									motor[rightBack] = 127;
									motor[leftBack] = 127;
							}
							this enables you to simply type driveForward() instead of having to repeat turning the motors on and off
	*/

	//below you will find code that is easier to read while maintaining the same lines of code you wrote

  while (true)
  {
  	int go;
  	go = 10;

  	//code to drive forward
  	if (vexRT[Ch2]> go) {
  		motor[port1] = 127; //rightback motor
  		motor[port2] = 127;	//leftback motor
  	}

  	//code to drive backward
  	else if (vexRT[Ch2]< go){
	motor[port1] = -127; //rightback motor
	motor[port2] = -127; //leftback motor
	}
	else {
		motor[port1] = 0; //rightback motor
		motor[port2] = 0; //leftback motor
	}

	//code to drive right
	if (vexRT[Ch4]> go) {
		motor[port1] = -127; //rightback motor
		motor[port2] = 127; //leftback motor
	}


	//code to drive left
	else if (vexRT[Ch4]< go) {
		motor[port1] = 127; //rightback motor
		motor[port2] = -127; //leftback motor
	}
	else{
		motor[port1] = 0; //rightback motor
		motor[port2] = 0; //leftback motor
	}


	//LS extend
	if (vexRT[Btn5U] == 1){
		motor[port2] = 127; //leftback motor, I believe you meant to type port3
		motor[port4] = 127; //LSback, LSleft would have been a better motor title name
	}
	else{
		motor[port3] = 0; //LSright
		motor[port4] = 0; //LSback
	}


	//LS retract
	if (vexRT[Btn5D] == 1) {
		motor[port3] = -127; //LSright
		motor[port4] = - 127; //LSback
	}
	else {
		motor[port3] = 0; //LSright
		motor[port4] = 0; //LSback
	}


	//claw up
	if (vexRT[Btn8U] == 1){
		motor[port5] = 127; //clawupdown
	}
	else {
		motor[port5] = 0; //clawupdown
	}


	//claw down
	if (vexRT[Btn8D] == 1){
		motor[port5] = -127; //clawupdown
	}
	else {
		motor[port5] = 0; //clawupdown
	}


	//claw open
	if (vexRT[Btn8L] == 1) {
		motor[port6] = 127; //clawopenclose
	}
	else {
		motor[port6] = 0; //clawopenclose
	}


	//claw close
	if (vexRT[Btn8R] == 1){
		motor[port6] = -127; //clawopenclose
	}
	else {
		motor[port6] = 0; //clawopenclose
	}

  }
}
