#pragma config(Motor,  port1,           RB,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LSR,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LSL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           CUD,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           COC,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

	void driveforward (){
		motor[RB] = 127;
  	motor[LB] = 127;
  	}


  	void driveback(){
  		motor[RB] = -127;
  	  motor[LB] = -127;
  	}


  void stopdrive (){
  	motor[RB] = 0;
		motor[LB] = 0;
	}

	void driveright(){
		motor[RB] = -127;
		motor[LB] = 127;
	}

	void driveleft(){
		motor[RB] = 127;
		motor[LB] = -127;
	}

task usercontrol()
{

  // User control code here, inside the loop
//RB = right back motor   LB = left back motor LSL = linear slide left      LSR = linear slide right    COC = claw open close   CUD  = claw up down




  while (true)
  {
  	int go;
  	go = 10;
// drive for  back motors and joysticks
  	if (vexRT[Ch2]> go) {
 		driveforward();
  	}
  	else if (vexRT[Ch2]< go){
  		driveback();
}
	else {
	stopdrive();
}



if (vexRT[Ch4]> go) {
	driveright();
}
	else if (vexRT[Ch4]< go) {
	driveleft();
}
	else{
	stopdrive();
}




// drive for linear slide
	if (vexRT[Btn5U] == 1){
	motor[port2] = 127;
	motor[port4] = 127;
}
	else{
	motor[port3] = 0;
	motor[port4] = 0;
}


	if (vexRT[Btn5D] == 1) {
	motor[port3] = -127;
	motor[port4] = - 127;
}
	else {
	motor[port3] = 0;
	motor[port4] = 0;
}

// drive for lifting up and down claw
	if (vexRT[Btn8U] == 1){
	motor[port5] = 127;
}
	else {
	motor[port5] = 0;
}


	if (vexRT[Btn8D] == 1){
		motor[port5] = -127;}
	else {
		motor[port5] = 0;}

	// drive for opining and closing claw

		if (vexRT[Btn8L] == 1) {
			motor[port6] = 127;
		}
		else {
			motor[port6] = 0;
		}



		if (vexRT[Btn8R] == 1){
			motor[port6] = -127;
		}
		else {
			motor[port6] = 0;
		}


    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}
